<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>3.5.16</version>
        <relativePath/>
    </parent>

    <groupId>com.starrainnotes</groupId>
    <artifactId>star-rain-parent</artifactId>
    <version>2.0.0</version>
    <packaging>pom</packaging>

    <properties>
        <java.version>21</java.version>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <modules>
        <module>star-rain-common</module>
        <module>star-rain-account</module>
        <module>star-rain-media</module>
        <module>star-rain-review</module>
        <module>star-rain-tutorial</module>
        <module>star-rain-blog</module>
        <module>star-rain-portfolio</module>
        <module>star-rain-message</module>
        <module>star-rain-english</module>
        <module>star-rain-profile</module>
        <module>star-rain-analytics</module>
        <module>star-rain-site</module>
        <module>star-rain-search</module>
        <module>star-rain-seo</module>
        <module>star-rain-boot</module>
    </modules>
</project>
