<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { ElMessage } from 'element-plus/es/components/index.mjs'
import type { ContentReview } from '@/api/account'
import type { ProblemDetail } from '@/api/http'
import { createPronunciationRule, fetchPronunciationRule, updatePronunciationRule } from '@/api/listening'
import type { MediaAsset } from '@/api/media'
import MarkdownEditor from '@/components/MarkdownEditor.vue'
import MediaPicker from '@/components/MediaPicker.vue'
import PublishChecklistDrawer, { type PublishCheck } from '@/components/english/PublishChecklistDrawer.vue'
import { useUnsavedGuard } from '@/composables/useUnsavedGuard'

const route = useRoute(); const router = useRouter(); const id = computed(() => Number(route.params.id)); const editing = computed(() => route.name === 'admin-listening-pronunciation-edit')
const loading = ref(false); const saving = ref(false); const mediaOpen = ref(false); const checkOpen = ref(false); const audioError = ref('')
const form = reactive({ ruleType: 'LINKING', title: '', summary: '', bodyMarkdown: '', audioMediaId: null as number|null, audioUrl: null as string|null, sortOrder: null as number|null })
const ruleTypes = ['LINKING','WEAK_FORM','ASSIMILATION','ELISION','STRESS','INTONATION']; const labels: Record<string,string> = {LINKING:'连读',WEAK_FORM:'弱读',ASSIMILATION:'同化',ELISION:'省音',STRESS:'重音',INTONATION:'语调'}
const checks = computed<PublishCheck[]>(() => [{key:'title',label:'标题完整',passed:!!form.title.trim()},{key:'summary',label:'摘要完整',passed:!!form.summary.trim()},{key:'body',label:'课程正文完整',passed:!!form.bodyMarkdown.trim()},{key:'audio',label:audioError.value||'示例音频可选；选择后必须能够播放',passed:!form.audioMediaId||!audioError.value}])
const { capture } = useUnsavedGuard(() => form, save)
function detailOf(error: unknown, fallback: string) { return (error as {response?:{data?:ProblemDetail}}).response?.data?.detail ?? fallback }
function isReview(value: unknown): value is ContentReview { return typeof value === 'object' && value !== null && 'contentType' in value }
async function load() { if (!editing.value) { capture(); return } if (!Number.isSafeInteger(id.value) || id.value < 1) { ElMessage.error('语音规则编号无效。'); return } loading.value = true; try { const rule = await fetchPronunciationRule(id.value); Object.assign(form,{ruleType:rule.ruleType,title:rule.title,summary:rule.summary,bodyMarkdown:rule.bodyMarkdown,audioMediaId:rule.audioMediaId,audioUrl:rule.audioUrl,sortOrder:rule.sortOrder}); capture() } catch(error) { ElMessage.error(detailOf(error,'加载语音规则失败。')) } finally { loading.value = false } }
function onAudio(asset: MediaAsset) { if (asset.assetType !== 'AUDIO') { ElMessage.warning('只能选择音频文件。'); return } form.audioMediaId=asset.id; form.audioUrl=asset.publicUrl; audioError.value=''; mediaOpen.value=false }
async function cancel() { await router.push({name:'admin-listening-pronunciation'}) }
async function save() { if(!form.title.trim()||!form.summary.trim()||!form.bodyMarkdown.trim()){ElMessage.warning('请完整填写标题、摘要和正文。');return} saving.value=true; const {audioUrl:_audioUrl,...payload}=form; try{const result=editing.value?await updatePronunciationRule(id.value,payload):await createPronunciationRule(payload); ElMessage.success(isReview(result)?'已提交审核，批准后应用到线上。':'语音规则已保存。'); capture(); await router.push({name:'admin-listening-pronunciation'})}catch(error){ElMessage.error(detailOf(error,'保存失败。'))}finally{saving.value=false} }
onMounted(load)
</script>
<template><section v-loading="loading" class="pronunciation-edit"><header><div><p>PRONUNCIATION · {{ editing ? '编辑规则' : '新建规则' }}</p><h1>{{ editing ? '编辑语音规则' : '创建语音规则' }}</h1><span>用完整正文与可选示例音频解释真实语流现象。</span></div><el-button @click="cancel">返回列表</el-button></header><el-form label-position="top" class="pronunciation-edit__form"><div class="pronunciation-edit__grid"><el-form-item label="规则类型"><el-select v-model="form.ruleType" style="width:100%"><el-option v-for="type in ruleTypes" :key="type" :label="`${labels[type]} · ${type}`" :value="type" /></el-select></el-form-item><el-form-item label="排序"><el-input-number v-model="form.sortOrder" :min="1" :step="10" /></el-form-item></div><el-form-item label="标题"><el-input v-model="form.title" /></el-form-item><el-form-item label="摘要"><el-input v-model="form.summary" type="textarea" :rows="3" /></el-form-item><el-form-item label="正文（Markdown，H2–H4 会生成前台目录）"><MarkdownEditor v-model="form.bodyMarkdown" placeholder="## 规则是什么&#10;&#10;解释、例句和跟读建议…" /></el-form-item><el-form-item label="示例音频（可选）"><audio v-if="form.audioUrl" :src="form.audioUrl" controls preload="metadata" @loadedmetadata="audioError=''" @error="audioError='音频无法播放，请检查文件、格式与 /uploads/ 访问权限'"/><el-alert v-if="audioError" :title="audioError" type="error" :closable="false"/><div><el-button @click="mediaOpen=true">上传或选择音频</el-button><el-button v-if="form.audioMediaId" @click="form.audioMediaId=null;form.audioUrl=null;audioError=''">移除</el-button></div></el-form-item><footer><el-button @click="checkOpen=true">发布检查</el-button><el-button @click="cancel">取消</el-button><el-button type="primary" :loading="saving" @click="save">保存规则</el-button></footer></el-form><MediaPicker v-model="mediaOpen" asset-type="AUDIO" allow-upload title="选择语音示例音频" @select="onAudio"/><PublishChecklistDrawer :open="checkOpen" :checks="checks" @close="checkOpen=false"/></section></template>
<style scoped>.pronunciation-edit{max-width:980px;margin:0 auto}.pronunciation-edit>header{display:flex;align-items:flex-end;justify-content:space-between;gap:20px;margin-bottom:24px}.pronunciation-edit>header p{margin:0;color:var(--accent);font-size:11px;font-weight:750;letter-spacing:.15em}.pronunciation-edit>header h1{margin:6px 0;font-size:clamp(28px,3vw,40px)}.pronunciation-edit>header span{color:var(--text-secondary);font-size:13px}.pronunciation-edit__form{padding:24px;border:1px solid var(--border);border-radius:20px;background:var(--bg-surface)}.pronunciation-edit__grid{display:grid;grid-template-columns:1fr 180px;gap:18px}.pronunciation-edit audio{width:100%;margin-bottom:10px}.pronunciation-edit footer{display:flex;justify-content:flex-end;gap:8px;padding-top:12px;border-top:1px solid var(--border)}@media(max-width:680px){.pronunciation-edit>header{align-items:flex-start;flex-direction:column}.pronunciation-edit__form{padding:18px}.pronunciation-edit__grid{grid-template-columns:1fr}.pronunciation-edit footer{flex-wrap:wrap}.pronunciation-edit footer :deep(.el-button){flex:1;margin-left:0}}</style>
