<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus/es/components/index.mjs'
import { addWordFamilyMember, createWordFamily, deleteWordFamily, deleteWordFamilyMember, fetchWordFamilies, moveWordFamilyMember, updateWordFamily, updateWordFamilyMember, type WordFamily, type WordFamilyMember } from '@/api/wordFamily'
const families=ref<WordFamily[]>([]);const selected=ref<WordFamily|null>(null);const q=ref('');const familyOpen=ref(false);const familyEditingId=ref<number|null>(null);const memberOpen=ref(false);const editingMember=ref<WordFamilyMember|null>(null)
const familyForm=reactive({headWord:'',slug:'',description:'',wordIds:''});const memberForm=reactive({spelling:'',partOfSpeech:'',phoneticUs:'',translation:'',cefrLevel:'',exampleSentence:'',exampleTranslation:''})
async function load(){try{families.value=await fetchWordFamilies(q.value);if(selected.value)selected.value=families.value.find(x=>x.id===selected.value?.id)||families.value[0]||null;else selected.value=families.value[0]||null}catch{ElMessage.error('加载词族失败。')}}
function newFamily(){familyEditingId.value=null;Object.assign(familyForm,{headWord:'',slug:'',description:'',wordIds:''});familyOpen.value=true}
function editFamily(){if(!selected.value)return;familyEditingId.value=selected.value.id;Object.assign(familyForm,{headWord:selected.value.headWord,slug:selected.value.slug,description:selected.value.description||'',wordIds:selected.value.wordIds.join(',')});familyOpen.value=true}
async function saveFamily(){const data={headWord:familyForm.headWord.trim(),slug:familyForm.slug.trim(),description:familyForm.description.trim()||null,wordIds:familyForm.wordIds.split(',').map(x=>x.trim()).filter(Boolean).map(Number).filter(Number.isFinite)};if(!data.headWord||!data.slug)return;try{if(familyEditingId.value){await updateWordFamily(familyEditingId.value,data)}else{await createWordFamily(data)}familyOpen.value=false;await load();ElMessage.success('词族已保存。')}catch(e:any){ElMessage.error(e.response?.data?.detail||'保存失败。')}}
function newMember(){editingMember.value=null;Object.assign(memberForm,{spelling:'',partOfSpeech:'',phoneticUs:'',translation:'',cefrLevel:'',exampleSentence:'',exampleTranslation:''});memberOpen.value=true}
function editMember(m:WordFamilyMember){editingMember.value=m;Object.assign(memberForm,{spelling:m.spelling,partOfSpeech:m.partOfSpeech||'',phoneticUs:m.phoneticUs||'',translation:m.translation||'',cefrLevel:m.cefrLevel||'',exampleSentence:m.exampleSentence||'',exampleTranslation:m.exampleTranslation||''});memberOpen.value=true}
async function saveMember(){if(!selected.value||!memberForm.spelling.trim())return;const data={...memberForm,spelling:memberForm.spelling.trim(),partOfSpeech:memberForm.partOfSpeech||null,phoneticUs:memberForm.phoneticUs||null,translation:memberForm.translation||null,cefrLevel:memberForm.cefrLevel||null,exampleSentence:memberForm.exampleSentence||null,exampleTranslation:memberForm.exampleTranslation||null};try{editingMember.value?await updateWordFamilyMember(selected.value.id,editingMember.value.id,data):await addWordFamilyMember(selected.value.id,data);memberOpen.value=false;await load()}catch(e:any){ElMessage.error(e.response?.data?.detail||'保存失败。')}}
async function removeFamily(){if(!selected.value)return;await ElMessageBox.confirm(`删除词族“${selected.value.headWord}”？`,'确认',{type:'warning'});await deleteWordFamily(selected.value.id);selected.value=null;await load()}
async function removeMember(m:WordFamilyMember){if(!selected.value)return;await deleteWordFamilyMember(selected.value.id,m.id);await load()}
async function move(m:WordFamilyMember,index:number){if(!selected.value)return;await moveWordFamilyMember(selected.value.id,m.id,index);await load()}
onMounted(load)
</script>
<template><section class="family"><header><div><p>WORD FAMILY · 词族扩展</p><h1>词族管理</h1><span>主词条保持简洁，派生词在这里维护音标、难度、释义与例句。</span></div><el-button type="primary" @click="newFamily">新建词族</el-button></header><div class="layout"><aside><el-input v-model="q" clearable placeholder="搜索词族" @input="load"/><button v-for="f in families" :key="f.id" :class="{active:selected?.id===f.id}" @click="selected=f"><strong>{{f.headWord}}</strong><span>{{f.members.length}} 个成员 · {{f.slug}}</span></button><p v-if="!families.length">暂无词族</p></aside><main v-if="selected"><div class="title"><div><p>{{selected.slug}}</p><h2>{{selected.headWord}}</h2><span>{{selected.description||'暂无说明'}}</span></div><div><el-button @click="editFamily">编辑</el-button><el-button type="danger" plain @click="removeFamily">删除</el-button><el-button type="primary" @click="newMember">添加成员</el-button></div></div><article v-for="(m,i) in selected.members" :key="m.id"><div><strong>{{m.spelling}}</strong><em>{{m.cefrLevel||'未分级'}}</em><span>{{m.partOfSpeech}} · {{m.phoneticUs}}</span><p>{{m.translation}}</p><small v-if="m.exampleSentence">{{m.exampleSentence}}<br/>{{m.exampleTranslation}}</small></div><nav><button :disabled="i===0" @click="move(m,i-1)">↑</button><button :disabled="i===selected.members.length-1" @click="move(m,i+1)">↓</button><button @click="editMember(m)">编辑</button><button class="danger" @click="removeMember(m)">删除</button></nav></article><div v-if="!selected.members.length" class="empty">这个词族还没有扩展成员。</div></main><main v-else class="empty">选择或新建一个词族开始维护。</main></div>
<el-dialog v-model="familyOpen" title="词族信息" width="520px"><el-form label-position="top"><el-form-item label="主词"><el-input v-model="familyForm.headWord"/></el-form-item><el-form-item label="Slug"><el-input v-model="familyForm.slug"/></el-form-item><el-form-item label="说明"><el-input v-model="familyForm.description" type="textarea"/></el-form-item><el-form-item label="关联单词 ID（逗号分隔）"><el-input v-model="familyForm.wordIds"/></el-form-item></el-form><template #footer><el-button @click="familyOpen=false">取消</el-button><el-button type="primary" @click="saveFamily">保存</el-button></template></el-dialog>
<el-dialog v-model="memberOpen" title="词族成员" width="600px"><el-form label-position="top"><div class="form-grid"><el-form-item label="拼写"><el-input v-model="memberForm.spelling"/></el-form-item><el-form-item label="词性"><el-input v-model="memberForm.partOfSpeech"/></el-form-item><el-form-item label="美式音标"><el-input v-model="memberForm.phoneticUs"/></el-form-item><el-form-item label="CEFR"><el-select v-model="memberForm.cefrLevel" clearable><el-option v-for="x in ['A1','A2','B1','B2','C1','C2']" :key="x" :value="x"/></el-select></el-form-item></div><el-form-item label="释义"><el-input v-model="memberForm.translation"/></el-form-item><el-form-item label="例句"><el-input v-model="memberForm.exampleSentence"/></el-form-item><el-form-item label="例句翻译"><el-input v-model="memberForm.exampleTranslation"/></el-form-item></el-form><template #footer><el-button @click="memberOpen=false">取消</el-button><el-button type="primary" @click="saveMember">保存</el-button></template></el-dialog></section></template>
<style scoped>.family{max-width:1380px;margin:auto}.family>header{display:flex;justify-content:space-between;align-items:end;gap:20px;margin-bottom:24px}.family header p{color:var(--accent);font-size:11px;font-weight:800;letter-spacing:.14em}.family h1{font-size:32px;margin:6px 0}.family header span{color:var(--text-secondary)}.layout{display:grid;grid-template-columns:300px minmax(0,1fr);gap:18px;min-height:600px}.layout>aside,.layout>main{border:1px solid var(--border);border-radius:18px;background:var(--bg-surface);padding:16px}.layout>aside button{display:flex;flex-direction:column;width:100%;text-align:left;padding:12px;margin-top:8px;border:0;border-radius:11px;background:transparent;color:var(--text-primary)}.layout>aside button:hover,.layout>aside button.active{background:color-mix(in srgb,var(--primary) 10%,transparent)}.layout>aside span{font-size:11px;color:var(--text-muted)}.title{display:flex;justify-content:space-between;gap:20px;padding:8px 4px 20px;border-bottom:1px solid var(--border)}.title h2{font-size:28px;margin:3px 0}.title p{font-family:monospace;color:var(--accent)}main>article{display:flex;justify-content:space-between;gap:18px;padding:16px 4px;border-bottom:1px solid var(--border)}article strong{font-size:18px}article em{margin-left:8px;color:var(--primary);font-size:11px;font-style:normal}article span,article p,article small{display:block;color:var(--text-secondary);margin-top:5px}article nav{display:flex;align-items:center;gap:5px}article nav button{border:0;background:transparent;color:var(--primary);cursor:pointer}.danger{color:var(--danger)!important}.empty{display:grid;place-items:center;color:var(--text-muted);min-height:260px}.form-grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}@media(max-width:800px){.family>header{align-items:stretch;flex-direction:column}.family>header>button{align-self:flex-start}.layout{grid-template-columns:1fr}.layout>aside{max-height:280px;overflow:auto}.title{flex-direction:column}.form-grid{grid-template-columns:1fr}}</style>
