<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { ElMessage } from 'element-plus/es/components/index.mjs'
import MarkdownEditor from '@/components/MarkdownEditor.vue'
import type { ContentReview } from '@/api/account'
import { createWritingPrompt, createWritingResource, getWritingPrompt, getWritingResource, updateWritingPrompt, updateWritingResource } from '@/api/writing'
const route=useRoute(),router=useRouter();const isPrompt=computed(()=>String(route.meta.kind)==='prompt');const id=computed(()=>Number(route.params.id||0));const saving=ref(false)
const form=reactive<any>({title:'',slug:'',summary:'',bodyMarkdown:'',backgroundMarkdown:'',requirementsMarkdown:'',cefrLevel:'B1',resourceKind:'EXPRESSION_LESSON',expressionLevel:'SENTENCE',wordMin:0,wordMax:300,estimatedMinutes:15,templateSchemaJson:'',rubricJson:'[]',checklistJson:'[]',tagIds:[]})
function isReview(value: unknown): value is ContentReview { return typeof value === 'object' && value !== null && 'contentType' in value }
async function load(){if(!id.value)return;try{Object.assign(form,isPrompt.value?await getWritingPrompt(id.value):await getWritingResource(id.value));form.tagIds=(form.tags||[]).map((x:any)=>x.id)}catch{ElMessage.error('加载写作内容失败。')}}
async function save(){if(!form.title.trim()||!form.slug.trim()||!form.summary.trim()){ElMessage.warning('请填写标题、slug 和摘要。');return}saving.value=true;try{let result;if(isPrompt.value){const payload={title:form.title,slug:form.slug,summary:form.summary,backgroundMarkdown:form.backgroundMarkdown,requirementsMarkdown:form.requirementsMarkdown,cefrLevel:form.cefrLevel,wordMin:form.wordMin,wordMax:form.wordMax,estimatedMinutes:form.estimatedMinutes,rubricJson:form.rubricJson||null,checklistJson:form.checklistJson||null,templateResourceId:form.templateResourceId||null,modelResourceId:form.modelResourceId||null,coverMediaId:null,sortOrder:form.sortOrder||10,tagIds:form.tagIds};result=id.value?await updateWritingPrompt(id.value,payload):await createWritingPrompt(payload)}else{const payload={resourceKind:form.resourceKind,expressionLevel:form.expressionLevel||null,title:form.title,slug:form.slug,summary:form.summary,bodyMarkdown:form.bodyMarkdown,coverMediaId:null,cefrLevel:form.cefrLevel,wordMin:form.wordMin,wordMax:form.wordMax,estimatedMinutes:form.estimatedMinutes,templateSchemaJson:form.resourceKind==='TEMPLATE'?form.templateSchemaJson:null,sortOrder:form.sortOrder||10,tagIds:form.tagIds};result=id.value?await updateWritingResource(id.value,payload):await createWritingResource(payload)}ElMessage.success(isReview(result)?'已提交审核，超级管理员批准后会应用到线上写作内容。':'已保存。');await router.push(String(route.query.return||'/admin/english/writing'))}catch(e:any){ElMessage.error(e?.response?.data?.detail||'保存失败。')}finally{saving.value=false}}
onMounted(()=>void load())
</script>
<template><section class="writing-edit"><header><div><p>ENGLISH WRITING · {{ isPrompt?'PRACTICE':'RESOURCE' }}</p><h1>{{ id?'编辑':'新建' }}{{isPrompt?'写作任务':'写作资源'}}</h1><span>前台正文目录只收录 H2–H4；页面标题保持唯一 H1。</span></div><div><el-button @click="router.push(String(route.query.return||'/admin/english/writing'))">取消</el-button><el-button type="primary" :loading="saving" @click="save">保存</el-button></div></header><div class="layout"><main><label>标题<el-input v-model="form.title"/></label><label>Slug<el-input v-model="form.slug"/></label><label>摘要<el-input v-model="form.summary" type="textarea" :rows="2"/></label><template v-if="isPrompt"><label>写作背景<MarkdownEditor v-model="form.backgroundMarkdown"/></label><label>写作要求<MarkdownEditor v-model="form.requirementsMarkdown"/></label></template><label v-else>正文（Markdown）<MarkdownEditor v-model="form.bodyMarkdown"/></label></main><aside><label>CEFR<el-select v-model="form.cefrLevel"><el-option v-for="x in ['A1','A2','B1','B2','C1','C2']" :key="x" :label="x" :value="x"/></el-select></label><template v-if="!isPrompt"><label>资源类型<el-select v-model="form.resourceKind"><el-option label="表达训练" value="EXPRESSION_LESSON"/><el-option label="文体课程" value="GENRE_LESSON"/><el-option label="范文" value="MODEL_ESSAY"/><el-option label="模板" value="TEMPLATE"/></el-select></label><label v-if="form.resourceKind==='EXPRESSION_LESSON'">表达层级<el-select v-model="form.expressionLevel"><el-option label="句子" value="SENTENCE"/><el-option label="段落" value="PARAGRAPH"/><el-option label="衔接" value="COHESION"/><el-option label="风格" value="STYLE"/></el-select></label><label v-if="form.resourceKind==='TEMPLATE'">模板结构 JSON<el-input v-model="form.templateSchemaJson" type="textarea" :rows="5" placeholder='{"version":1,"blocks":[]}'/></label></template><label>最少词数<el-input-number v-model="form.wordMin" :min="0"/></label><label>最多词数<el-input-number v-model="form.wordMax" :min="0"/></label><label>预计分钟<el-input-number v-model="form.estimatedMinutes" :min="0"/></label><template v-if="isPrompt"><label>评分量表 JSON<el-input v-model="form.rubricJson" type="textarea" :rows="4"/></label><label>自检清单 JSON<el-input v-model="form.checklistJson" type="textarea" :rows="4"/></label></template></aside></div></section></template>
<style scoped>.writing-edit{max-width:1380px;margin:auto}header{position:sticky;z-index:4;top:0;display:flex;justify-content:space-between;gap:16px;align-items:end;padding:18px 0;background:var(--bg-page)}header p{margin:0;color:var(--accent);font-size:11px;font-weight:800;letter-spacing:.14em}h1{font-size:28px;margin:6px 0}header span{font-size:13px;color:var(--text-secondary)}.layout{display:grid;grid-template-columns:minmax(0,1fr) 330px;gap:20px}.layout main,.layout aside{display:flex;flex-direction:column;gap:16px}.layout aside{padding:18px;border:1px solid var(--border);border-radius:16px;background:var(--bg-surface);height:max-content}label{display:flex;flex-direction:column;gap:7px;font-size:13px;font-weight:700;color:var(--text-secondary)}@media(max-width:900px){.layout{grid-template-columns:1fr}.layout aside{order:-1}}@media(max-width:620px){header{align-items:flex-start;flex-direction:column}header span{display:none}}</style>
