<script setup lang="ts">
import { onMounted, reactive, ref, watch } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { ElMessage, ElMessageBox } from 'element-plus/es/components/index.mjs'
import { deleteWritingPrompt, deleteWritingResource, fetchWritingPrompts, fetchWritingResources, publishWritingPrompt, publishWritingResource, withdrawWritingPrompt, withdrawWritingResource, type WritingPage, type WritingPromptSummary, type WritingResourceSummary } from '@/api/writing'
const route=useRoute(),router=useRouter();const tab=ref<'resources'|'prompts'>('resources');const resourcePage=ref<WritingPage<WritingResourceSummary>>(),promptPage=ref<WritingPage<WritingPromptSummary>>();const loading=ref(false);const loadError=ref('');const filters=reactive({q:'',status:'',kind:'',cefr:''})
function sync(){tab.value=route.query.tab==='prompts'?'prompts':'resources';filters.q=String(route.query.q??'');filters.status=String(route.query.status??'');filters.kind=String(route.query.kind??'');filters.cefr=String(route.query.cefr??'')}
function write(){void router.push({query:{tab:tab.value==='resources'?undefined:'prompts',q:filters.q||undefined,status:filters.status||undefined,kind:tab.value==='resources'?(filters.kind||undefined):undefined,cefr:filters.cefr||undefined}})}
async function load(){loading.value=true;loadError.value='';try{if(tab.value==='resources')resourcePage.value=await fetchWritingResources({page:1,pageSize:50,q:filters.q||undefined,status:filters.status||undefined,kind:filters.kind||undefined,cefr:filters.cefr||undefined});else promptPage.value=await fetchWritingPrompts({page:1,pageSize:50,q:filters.q||undefined,status:filters.status||undefined,cefr:filters.cefr||undefined})}catch(error:any){loadError.value=error?.response?.data?.detail||error?.message||'请求未能到达写作接口。';ElMessage.error(`加载写作内容失败：${loadError.value}`)}finally{loading.value=false}}
async function state(item:WritingResourceSummary|WritingPromptSummary,publish:boolean){try{if(tab.value==='resources')publish?await publishWritingResource(item.id):await withdrawWritingResource(item.id);else publish?await publishWritingPrompt(item.id):await withdrawWritingPrompt(item.id);ElMessage.success(publish?'已发布。':'已撤回。');await load()}catch{ElMessage.error('操作未完成，请先检查发布清单。')}}
async function remove(item:WritingResourceSummary|WritingPromptSummary){try{await ElMessageBox.confirm(`确定删除「${item.title}」？`,'删除确认',{type:'warning'});if(tab.value==='resources')await deleteWritingResource(item.id);else await deleteWritingPrompt(item.id);await load()}catch{/* cancel */}}
function create(){router.push({name:tab.value==='resources'?'admin-writing-resource-new':'admin-writing-prompt-new',query:{return:route.fullPath}})}function edit(id:number){router.push({name:tab.value==='resources'?'admin-writing-resource-edit':'admin-writing-prompt-edit',params:{id},query:{return:route.fullPath}})}function exercise(id:number){router.push({name:'admin-writing-exercises',params:{id},query:{return:route.fullPath}})}
onMounted(()=>{sync();void load()});watch(()=>route.query,()=>{sync();void load()})
</script>
<template><section class="writing-manage"><header><div><p>ENGLISH WRITING · 表达与实践</p><h1>写作管理</h1><span>表达训练、文体课程、范文模板与写作任务各自维护，并使用共享语义标签。</span></div><el-button type="primary" @click="create">{{ tab==='resources'?'新建资源':'新建任务' }}</el-button></header><div class="tabs"><button :class="{active:tab==='resources'}" @click="router.push({query:{...route.query,tab:undefined}})">学习资源</button><button :class="{active:tab==='prompts'}" @click="router.push({query:{...route.query,tab:'prompts'}})">写作任务</button></div><div class="filters"><el-input v-model="filters.q" placeholder="搜索标题/摘要" clearable @keyup.enter="write" @clear="write"/><el-select v-model="filters.status" clearable placeholder="状态" @change="write"><el-option label="草稿" value="DRAFT"/><el-option label="已发布" value="PUBLISHED"/><el-option label="已撤回" value="WITHDRAWN"/></el-select><el-select v-if="tab==='resources'" v-model="filters.kind" clearable placeholder="资源类型" @change="write"><el-option label="表达训练" value="EXPRESSION_LESSON"/><el-option label="文体课程" value="GENRE_LESSON"/><el-option label="范文库" value="MODEL_ESSAY"/><el-option label="写作模板" value="TEMPLATE"/></el-select><el-select v-model="filters.cefr" clearable placeholder="CEFR" @change="write"><el-option v-for="x in ['A1','A2','B1','B2','C1','C2']" :key="x" :label="x" :value="x"/></el-select></div><el-alert v-if="loadError" title="写作接口暂时不可用" :description="loadError" type="error" show-icon :closable="false" style="margin-bottom:16px"/><div v-loading="loading" class="cards"><p v-if="!loading && !loadError && !(tab==='resources'?resourcePage?.items:promptPage?.items)?.length" class="empty">暂无内容，请创建第一项。</p><article v-for="item in tab==='resources'?resourcePage?.items:promptPage?.items" :key="item.id" class="card"><img v-if="item.coverUrl" :src="item.coverUrl" :alt="item.title"><div v-else class="cover">{{ tab==='resources'?'写':'练' }}</div><div class="body"><div class="meta"><b>{{ 'resourceKind' in item ? item.resourceKind : 'WRITING_PROMPT' }}</b><span>{{ item.cefrLevel }} · {{ item.publishStatus }}</span></div><h2>{{ item.title }}</h2><p>{{ item.summary }}</p><div class="tags"><i v-for="tag in item.tags" :key="tag.id">{{ tag.name }}</i></div><footer><el-button link type="primary" @click="edit(item.id)">编辑</el-button><el-button v-if="tab==='prompts'" link @click="exercise(item.id)">练习</el-button><el-button v-if="item.publishStatus!=='PUBLISHED'" link type="success" @click="state(item,true)">发布</el-button><el-button v-else link type="warning" @click="state(item,false)">撤回</el-button><el-button link type="danger" @click="remove(item)">删除</el-button></footer></div></article></div></section></template>
<style scoped>.writing-manage{max-width:1380px;margin:auto}header{display:flex;justify-content:space-between;align-items:end;margin-bottom:22px}header p{margin:0;color:var(--accent);font-size:11px;font-weight:800;letter-spacing:.14em}h1{margin:7px 0;font-size:32px}header span,.body p{color:var(--text-secondary);font-size:13px}.tabs{display:flex;gap:8px;margin-bottom:16px}.tabs button{border:1px solid var(--border);background:var(--bg-surface);color:var(--text-secondary);padding:9px 15px;border-radius:10px;cursor:pointer}.tabs button.active{color:var(--primary);border-color:var(--primary);background:color-mix(in srgb,var(--primary) 8%,var(--bg-surface))}.filters{display:flex;gap:10px;flex-wrap:wrap;margin-bottom:20px}.filters :deep(.el-input){width:240px}.filters :deep(.el-select){width:140px}.cards{display:grid;grid-template-columns:repeat(auto-fill,minmax(330px,1fr));gap:16px;min-height:100px}.card{display:flex;overflow:hidden;border:1px solid var(--border);border-radius:18px;background:var(--bg-surface)}.card img,.cover{width:92px;min-height:100%;object-fit:cover;flex-shrink:0}.cover{display:grid;place-items:center;color:var(--primary);font-weight:900;font-size:30px;background:linear-gradient(135deg,color-mix(in srgb,var(--primary) 16%,var(--bg-surface)),var(--bg-subtle))}.body{min-width:0;padding:15px;flex:1}.meta{display:flex;justify-content:space-between;gap:8px;font-size:11px;color:var(--text-muted)}.meta b{color:var(--accent);font-size:10px}.body h2{font-size:17px;margin:8px 0 5px}.body p{margin:0;line-height:1.55;display:-webkit-box;-webkit-line-clamp:2;-webkit-box-orient:vertical;overflow:hidden}.tags{display:flex;gap:4px;flex-wrap:wrap;margin:10px 0}.tags i{font-style:normal;font-size:11px;padding:2px 7px;border:1px solid var(--border);border-radius:999px;color:var(--text-secondary)}footer{display:flex;gap:4px}.empty{color:var(--text-muted);grid-column:1/-1}@media(max-width:720px){header{align-items:flex-start;gap:14px}header span{display:none}.filters :deep(.el-input),.filters :deep(.el-select){width:100%}.cards{grid-template-columns:1fr}}@media(prefers-reduced-motion:reduce){*{transition:none!important}}</style>
