<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { ElMessage, ElMessageBox } from 'element-plus/es/components/index.mjs'
import { createWritingExercise, deleteWritingExercise, fetchWritingExercises, getWritingPrompt, moveWritingExercise, updateWritingExercise, type WritingExercise } from '@/api/writing'
const route=useRoute(),router=useRouter(),id=Number(route.params.id);const title=ref('');const items=ref<WritingExercise[]>([]);const loading=ref(true),open=ref(false),editing=ref<number|null>(null),saving=ref(false)
const types=['SENTENCE_REWRITE','SENTENCE_COMBINE','COHESION_FILL','STYLE_ANALYSIS'];const form=reactive({questionType:types[0],promptMarkdown:'',configJson:'{"answer":""}',explanationMarkdown:'',scoreValue:1,publishStatus:'DRAFT'})
async function load(){loading.value=true;try{const[p,list]=await Promise.all([getWritingPrompt(id),fetchWritingExercises(id)]);title.value=p.title;items.value=list}catch{ElMessage.error('加载写作练习失败。')}finally{loading.value=false}}
function fresh(){editing.value=null;Object.assign(form,{questionType:types[0],promptMarkdown:'',configJson:'{"answer":""}',explanationMarkdown:'',scoreValue:1,publishStatus:'DRAFT'});open.value=true}function edit(x:WritingExercise){editing.value=x.id;Object.assign(form,{questionType:x.questionType,promptMarkdown:x.promptMarkdown,configJson:JSON.stringify(x.config),explanationMarkdown:x.explanationMarkdown||'',scoreValue:x.scoreValue,publishStatus:x.publishStatus});open.value=true}
async function save(){saving.value=true;try{const payload={...form,explanationMarkdown:form.explanationMarkdown||null};editing.value?await updateWritingExercise(id,editing.value,payload):await createWritingExercise(id,payload);open.value=false;await load();ElMessage.success('已保存。')}catch(e:any){ElMessage.error(e?.response?.data?.detail||'保存失败，请检查题型配置。')}finally{saving.value=false}}
async function remove(x:WritingExercise){try{await ElMessageBox.confirm('确定删除这道练习？','删除确认',{type:'warning'});await deleteWritingExercise(id,x.id);await load()}catch{/* canceled */}}async function move(index:number,offset:number){const target=index+offset;if(target<0||target>=items.value.length)return;await moveWritingExercise(id,items.value[index].id,target);await load()}onMounted(()=>void load())
</script>
<template><section class="writing-exercises"><header><div><p>WRITING EXERCISES · 安全评分</p><h1>{{title||'写作任务练习'}}</h1><span>仅发布题目会对前台可见；标准答案始终留在服务端。</span></div><div><el-button @click="router.push(String(route.query.return||'/admin/english/writing?tab=prompts'))">返回任务</el-button><el-button type="primary" @click="fresh">新建练习</el-button></div></header><div v-loading="loading" class="list"><p v-if="!loading&&!items.length" class="empty">暂无练习。</p><article v-for="(x,index) in items" :key="x.id"><div><b>{{x.questionType}}</b><span>{{x.publishStatus}} · {{x.scoreValue}} 分</span></div><p>{{x.promptMarkdown}}</p><pre>{{JSON.stringify(x.config,null,2)}}</pre><footer><el-button link type="primary" @click="edit(x)">编辑</el-button><el-button link :disabled="index===0" @click="move(index,-1)">上移</el-button><el-button link :disabled="index===items.length-1" @click="move(index,1)">下移</el-button><el-button link type="danger" @click="remove(x)">删除</el-button></footer></article></div><el-dialog v-model="open" :title="editing?'编辑练习':'新建练习'" width="min(680px,94vw)"><el-form label-position="top"><el-form-item label="题型"><el-select v-model="form.questionType"><el-option v-for="x in types" :key="x" :value="x"/></el-select></el-form-item><el-form-item label="题干（Markdown）"><el-input v-model="form.promptMarkdown" type="textarea" :rows="3"/></el-form-item><el-form-item label="配置 JSON（必须含 answer 或 answers）"><el-input v-model="form.configJson" type="textarea" :rows="7"/></el-form-item><el-form-item label="解析"><el-input v-model="form.explanationMarkdown" type="textarea" :rows="2"/></el-form-item><el-form-item label="分值"><el-input-number v-model="form.scoreValue" :min="1" :max="100"/></el-form-item><el-form-item label="状态"><el-radio-group v-model="form.publishStatus"><el-radio value="DRAFT">草稿</el-radio><el-radio value="PUBLISHED">发布</el-radio></el-radio-group></el-form-item></el-form><template #footer><el-button @click="open=false">取消</el-button><el-button type="primary" :loading="saving" @click="save">保存</el-button></template></el-dialog></section></template>
<style scoped>.writing-exercises{max-width:1100px;margin:auto}header{display:flex;justify-content:space-between;align-items:end;gap:14px;margin-bottom:22px}header p{margin:0;color:var(--accent);font-size:11px;font-weight:800;letter-spacing:.14em}h1{margin:7px 0;font-size:28px}header span{color:var(--text-secondary);font-size:13px}.list{display:grid;gap:12px;min-height:100px}.list article{padding:16px;border:1px solid var(--border);border-radius:15px;background:var(--bg-surface)}.list article>div{display:flex;justify-content:space-between;font-size:12px;color:var(--text-muted)}.list article b{color:var(--primary)}.list p{white-space:pre-wrap}.list pre{max-height:180px;overflow:auto;padding:10px;border-radius:8px;background:var(--bg-subtle);font-size:12px}.empty{color:var(--text-muted)}@media(max-width:620px){header{align-items:flex-start;flex-direction:column}header span{display:none}}</style>
