package com.starrainnotes.tutorial.learning.mapper;
import com.starrainnotes.tutorial.learning.entity.EvidenceModels.*;
import com.starrainnotes.tutorial.learning.dto.LearningPageQueryDTO;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface EvidenceLearningMapper {
    int saveSessionSummary(@Param("accountId") Long accountId, @Param("id") Long id, @Param("summaryJson") String summaryJson);
    Session latestInitial(@Param("accountId") Long accountId, @Param("chapterId") Long chapterId);
    int ensureAccountLock(@Param("accountId") Long accountId);
    Long lockAccount(@Param("accountId") Long accountId);
    List<Plan> listPlans(@Param("accountId") Long accountId);
    List<Plan> currentPlans(@Param("accountId") Long accountId);
    List<Plan> planHistory(@Param("accountId") Long accountId, @Param("query") LearningPageQueryDTO query);
    long countPlanHistory(@Param("accountId") Long accountId, @Param("query") LearningPageQueryDTO query);
    Plan plan(@Param("accountId") Long accountId, @Param("id") Long id);
    int restartPlan(@Param("accountId") Long accountId, @Param("id") Long id);
    int clearPlanCompletion(@Param("accountId") Long accountId, @Param("id") Long id);
    int completePlanChapter(@Param("accountId") Long accountId, @Param("sessionId") Long sessionId);
    Session planSession(@Param("accountId") Long accountId, @Param("chapterId") Long chapterId, @Param("planId") Long planId);
    List<Session> openInitialSessions(@Param("accountId") Long accountId, @Param("chapterId") Long chapterId);
    int insertSessionQuestion(@Param("sessionId") Long sessionId, @Param("questionId") Long questionId, @Param("baselineVersion") int baselineVersion);
    List<Long> answeredForSession(@Param("accountId") Long accountId, @Param("sessionId") Long sessionId);
    int insertPlan(@Param("row") Plan row);
    int updatePlan(@Param("row") Plan row);
    int planStatus(@Param("accountId") Long accountId, @Param("id") Long id, @Param("status") String status);
    List<Chapter> planChapters(@Param("accountId") Long accountId, @Param("planId") Long planId);
    List<Long> conflictingChapters(@Param("accountId") Long accountId, @Param("excludePlanId") Long excludePlanId);
    int insertPlanChapter(@Param("row") Chapter row);
    int deletePlanChapters(@Param("accountId") Long accountId, @Param("planId") Long planId);
    int insertTask(@Param("row") Task row);
    int insertTaskChapter(@Param("taskId") Long taskId, @Param("row") Chapter row, @Param("sequenceNo") int sequenceNo);
    List<Task> tasks(@Param("accountId") Long accountId, @Param("planId") Long planId);
    Task task(@Param("accountId") Long accountId, @Param("id") Long id);
    List<Chapter> taskChapters(@Param("accountId") Long accountId, @Param("taskId") Long taskId);
    int deleteTaskChapters(@Param("accountId") Long accountId, @Param("planId") Long planId);
    int deleteTasks(@Param("accountId") Long accountId, @Param("planId") Long planId);
    int startTask(@Param("accountId") Long accountId, @Param("id") Long id);
    int reconcileTasks(@Param("accountId") Long accountId);
    int reconcilePlans(@Param("accountId") Long accountId);
    Session session(@Param("accountId") Long accountId, @Param("id") Long id);
    Session currentInitial(@Param("accountId") Long accountId, @Param("chapterId") Long chapterId);
    Session currentReview(@Param("accountId") Long accountId);
    int insertSession(@Param("row") Session row);
    int sessionStatus(@Param("accountId") Long accountId, @Param("id") Long id, @Param("status") String status);
    List<Item> items(@Param("accountId") Long accountId, @Param("sessionId") Long sessionId);
    int insertItem(@Param("row") Item row);
    int revealItem(@Param("accountId") Long accountId, @Param("sessionId") Long sessionId, @Param("cardId") Long cardId);
    int completeItem(@Param("accountId") Long accountId, @Param("sessionId") Long sessionId, @Param("cardId") Long cardId);
    List<Long> initialCardIds(@Param("accountId") Long accountId, @Param("chapterId") Long chapterId);
    int insertEvidence(@Param("row") Evidence row);
    List<Evidence> cardEvidence(@Param("accountId") Long accountId, @Param("cardId") Long cardId);
    List<Evidence> sessionEvidence(@Param("accountId") Long accountId, @Param("sessionId") Long sessionId);
    List<Mastery> masteries(@Param("accountId") Long accountId);
    int upsertMastery(@Param("row") Mastery row);
    Answer answer(@Param("accountId") Long accountId, @Param("questionId") Long questionId);
    int insertAnswer(@Param("row") Answer row);
    int insertAnswerVersion(@Param("row") AnswerVersion row);
    List<AnswerVersion> answerVersions(@Param("accountId") Long accountId, @Param("questionId") Long questionId);
    int updateAnswerHeader(@Param("row") Answer row);
    List<Long> answeredQuestionIds(@Param("accountId") Long accountId);
    List<Session> historySessions(@Param("accountId") Long accountId, @Param("offset") int offset, @Param("limit") int limit);
    long countHistorySessions(@Param("accountId") Long accountId);
    List<Session> filteredHistory(@Param("accountId") Long accountId, @Param("query") LearningPageQueryDTO query);
    long countFilteredHistory(@Param("accountId") Long accountId, @Param("query") LearningPageQueryDTO query);
    List<TutorialOption> historyTutorials(@Param("accountId") Long accountId);
}
