# Copy this file to application-local-secret.yml and fill values locally.
# application-local-secret.yml is ignored by Git.
spring:
  datasource:
    password:

app:
  setup-token:
  account:
    super-admin-email:
    mail:
      host:
      port: 465
      username:
      auth-code:
      from:
      ssl-enabled: true
      base-url: http://localhost:5173

