package com.starrainnotes.english.writing.service;

import com.baomidou.mybatisplus.core.conditions.query.LambdaQueryWrapper;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.starrainnotes.common.error.ApiException;
import com.starrainnotes.common.slug.NumericSlugGenerator;
import com.starrainnotes.seo.SeoContentChange;
import com.starrainnotes.english.writing.dto.*;
import com.starrainnotes.english.writing.entity.WritingResource;
import com.starrainnotes.english.writing.mapper.WritingResourceMapper;
import com.starrainnotes.site.service.SiteSettingsTimezone;
import org.springframework.dao.DuplicateKeyException;
import org.springframework.http.HttpStatus;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.format.DateTimeFormatter;
import java.util.*;

/** 独立写作资源域；所有可发布性校验在服务端完成。 */
@Service
public class WritingResourceService {
    private static final Set<String> KINDS=Set.of("EXPRESSION_LESSON","GENRE_LESSON","MODEL_ESSAY","TEMPLATE");
    private static final Set<String> LEVELS=Set.of("SENTENCE","PARAGRAPH","COHESION","STYLE");
    private static final DateTimeFormatter ISO=DateTimeFormatter.ISO_OFFSET_DATE_TIME;
    private static final String BASE="""
      SELECT r.*,m.public_url cover_url FROM english_writing_resource r LEFT JOIN media_asset m ON m.id=r.cover_media_id
      """;
    private final WritingResourceMapper mapper; private final JdbcTemplate jdbc; private final ObjectMapper json; private final SiteSettingsTimezone timezone;
    public WritingResourceService(WritingResourceMapper mapper,JdbcTemplate jdbc,ObjectMapper json,SiteSettingsTimezone timezone){this.mapper=mapper;this.jdbc=jdbc;this.json=json;this.timezone=timezone;}

    @Transactional public WritingResourceView create(WritingResourceRequest r){
        validateRequest(r); String slug=NumericSlugGenerator.forCreate(r.slug(),this::slugExists); WritingResource e=new WritingResource(); apply(e,r,slug); e.setPublishStatus("DRAFT"); e.setSortOrder(r.sortOrder()==null?nextOrder():r.sortOrder());
        try{mapper.insert(e);}catch(DuplicateKeyException x){throw conflict();} replaceTags(e.getId(),r.tagIds()); return get(e.getId());
    }
    @Transactional @SeoContentChange(table="english_writing_resource",pathPrefix="/english/writing/resources/") public WritingResourceView update(Long id,WritingResourceRequest r){WritingResource e=require(id);validateRequest(r);String slug=NumericSlugGenerator.forUpdate(r.slug(),e.getSlug());assertSlug(slug,id);apply(e,r,slug);try{mapper.updateById(e);}catch(DuplicateKeyException x){throw conflict();}replaceTags(id,r.tagIds());return get(id);}
    public WritingResourceView get(Long id){WritingResource e=require(id);return jdbc.queryForObject(BASE+" WHERE r.id=?",this::mapView,id);}
    public WritingResourceView publicGet(String slug){try{return jdbc.queryForObject(BASE+" WHERE r.slug=? AND r.publish_status='PUBLISHED'",this::mapView,slug);}catch(Exception x){throw unavailable();}}
    public WritingPageView<WritingResourceSummaryView> list(int page,int pageSize,String q,String kind,String level,String cefr,String status,Long topic,Long genre){
        List<Object> p=new ArrayList<>();String where=where(q,kind,level,cefr,status,topic,genre,p);return page(page,pageSize,where,p);
    }
    public WritingPageView<WritingResourceSummaryView> publicList(int page,int pageSize,String q,String kind,String level,String cefr,Long topic,Long genre){List<Object> p=new ArrayList<>();String where=where(q,kind,level,cefr,"PUBLISHED",topic,genre,p);return page(page,pageSize,where,p);}
    @Transactional @SeoContentChange(table="english_writing_resource",pathPrefix="/english/writing/resources/") public WritingResourceView publish(Long id){WritingResource e=require(id); List<String> bad=publishProblems(e); if(!bad.isEmpty())throw new ApiException(HttpStatus.UNPROCESSABLE_ENTITY,"ENGLISH_WRITING_PUBLISH_INVALID","Cannot publish",String.join("; ",bad));jdbc.update("UPDATE english_writing_resource SET publish_status='PUBLISHED',published_at=COALESCE(published_at,UTC_TIMESTAMP(6)) WHERE id=?",id);return get(id);}
    @Transactional @SeoContentChange(table="english_writing_resource",pathPrefix="/english/writing/resources/") public WritingResourceView withdraw(Long id){WritingResource e=require(id);if("DRAFT".equals(e.getPublishStatus()))throw new ApiException(HttpStatus.UNPROCESSABLE_ENTITY,"ENGLISH_INVALID_PUBLISH_TRANSITION","Invalid publish transition","A draft cannot be withdrawn.");jdbc.update("UPDATE english_writing_resource SET publish_status='WITHDRAWN' WHERE id=?",id);return get(id);}
    @Transactional public void delete(Long id){WritingResource e=require(id);if("PUBLISHED".equals(e.getPublishStatus()))throw new ApiException(HttpStatus.CONFLICT,"ENGLISH_WRITING_PUBLISHED_DELETE_FORBIDDEN","Published resource cannot be deleted","Withdraw it first."); Integer refs=jdbc.queryForObject("SELECT COUNT(*) FROM english_writing_prompt WHERE template_resource_id=? OR model_resource_id=?",Integer.class,id,id);if(refs!=null&&refs>0)throw new ApiException(HttpStatus.CONFLICT,"ENGLISH_WRITING_RESOURCE_IN_USE","Resource is in use","Remove prompt references first.");mapper.deleteById(id);}
    @Transactional public void move(Long id,int index){require(id);List<Long> ids=jdbc.queryForList("SELECT id FROM english_writing_resource ORDER BY sort_order,id",Long.class);ids.remove(id);ids.add(Math.min(Math.max(index,0),ids.size()),id);for(int i=0;i<ids.size();i++)jdbc.update("UPDATE english_writing_resource SET sort_order=? WHERE id=?",(i+1)*10,ids.get(i));}

    private WritingPageView<WritingResourceSummaryView> page(int page,int size,String where,List<Object> p){int safePage=Math.max(1,page), safeSize=Math.min(50,Math.max(1,size));Long total=jdbc.queryForObject("SELECT COUNT(*) FROM english_writing_resource r "+where,Long.class,p.toArray());List<WritingResourceSummaryView> rows=jdbc.query(BASE+where+" ORDER BY r.sort_order,r.id LIMIT "+safeSize+" OFFSET "+((safePage-1)*safeSize),p.toArray(),(rs,n)->summary(rs));Map<Long,List<WritingTagRef>> tags=tags(rows.stream().map(WritingResourceSummaryView::id).toList());return new WritingPageView<>(rows.stream().map(x->x.withTags(tags.getOrDefault(x.id(),List.of()))).toList(),safePage,safeSize,total==null?0:total,total==null||total==0?0:(int)((total+safeSize-1)/safeSize));}
    private String where(String q,String kind,String level,String cefr,String status,Long topic,Long genre,List<Object> p){StringBuilder w=new StringBuilder(" WHERE 1=1");if(q!=null&&!q.isBlank()){w.append(" AND (r.title LIKE ? OR r.summary LIKE ?)");p.add("%"+q.trim()+"%");p.add("%"+q.trim()+"%");}if(kind!=null&&!kind.isBlank()){w.append(" AND r.resource_kind=?");p.add(kind);}if(level!=null&&!level.isBlank()){w.append(" AND r.expression_level=?");p.add(level);}if(cefr!=null&&!cefr.isBlank()){w.append(" AND r.cefr_level=?");p.add(cefr);}if(status!=null&&!status.isBlank()){w.append(" AND r.publish_status=?");p.add(status);}tagWhere(w,p,topic,"TOPIC");tagWhere(w,p,genre,"GENRE");return w.toString();}
    private void tagWhere(StringBuilder w,List<Object> p,Long id,String dimension){if(id!=null){w.append(" AND EXISTS (SELECT 1 FROM english_writing_resource_tag wt JOIN english_taxonomy_term t ON t.id=wt.term_id WHERE wt.resource_id=r.id AND wt.term_id=? AND t.dimension=?)");p.add(id);p.add(dimension);}}
    private void validateRequest(WritingResourceRequest r){if(!KINDS.contains(r.resourceKind()))invalid("Unknown resource kind");if(r.expressionLevel()!=null&&!r.expressionLevel().isBlank()&&!LEVELS.contains(r.expressionLevel()))invalid("Unknown expression level");if("EXPRESSION_LESSON".equals(r.resourceKind())&&(r.expressionLevel()==null||r.expressionLevel().isBlank()))invalid("Expression lessons require expressionLevel");if(!"EXPRESSION_LESSON".equals(r.resourceKind())&&r.expressionLevel()!=null&&!r.expressionLevel().isBlank())invalid("expressionLevel is only allowed for expression lessons");if(!"TEMPLATE".equals(r.resourceKind())&&r.templateSchemaJson()!=null&&!r.templateSchemaJson().isBlank())invalid("Only templates may contain templateSchemaJson");if(r.wordMin()!=null&&r.wordMin()<0||r.wordMax()!=null&&r.wordMax()<0||r.wordMin()!=null&&r.wordMax()!=null&&r.wordMin()>r.wordMax())invalid("Invalid word range");if(r.estimatedMinutes()!=null&&r.estimatedMinutes()<0)invalid("Invalid time");cefr(r.cefrLevel());cover(r.coverMediaId());if("TEMPLATE".equals(r.resourceKind()))validateTemplate(r.templateSchemaJson());}
    private void validateTemplate(String raw){if(raw==null||raw.isBlank())invalid("Templates require a schema");try{JsonNode root=json.readTree(raw);if(!root.isObject()||root.path("version").asInt()!=1||!root.path("blocks").isArray())invalid("Invalid template schema");Set<String> seen=new HashSet<>();for(JsonNode n:root.path("blocks")){String id=n.path("id").asText();String type=n.path("type").asText();if(!id.matches("[a-z0-9]+(?:-[a-z0-9]+)*")||!seen.add(id)||!(type.equals("text")||type.equals("textarea")))invalid("Invalid template block");}}catch(Exception e){if(e instanceof ApiException)throw (ApiException)e;invalid("Invalid template schema JSON");}}
    private void apply(WritingResource e,WritingResourceRequest r,String slug){e.setResourceKind(r.resourceKind());e.setExpressionLevel(clean(r.expressionLevel()));e.setTitle(r.title().trim());e.setSlug(slug);e.setSummary(r.summary().trim());e.setBodyMarkdown(r.bodyMarkdown());e.setCoverMediaId(r.coverMediaId());e.setCefrLevel(r.cefrLevel());e.setWordMin(r.wordMin());e.setWordMax(r.wordMax());e.setEstimatedMinutes(r.estimatedMinutes()==null?0:r.estimatedMinutes());e.setTemplateSchemaJson(clean(r.templateSchemaJson()));if(r.sortOrder()!=null)e.setSortOrder(r.sortOrder());}
    private List<String> publishProblems(WritingResource e){List<String>b=new ArrayList<>();if(e.getTitle()==null||e.getTitle().isBlank())b.add("标题不能为空");if(e.getBodyMarkdown()==null||e.getBodyMarkdown().isBlank())b.add("正文不能为空");if(!hasTags(e.getId(),"TOPIC")&&!hasTags(e.getId(),"GENRE"))b.add("至少需要主题或文体标签");if("TEMPLATE".equals(e.getResourceKind())&&(e.getTemplateSchemaJson()==null||e.getTemplateSchemaJson().isBlank()))b.add("模板必须有结构");return b;}
    private boolean hasTags(Long id,String d){Integer c=jdbc.queryForObject("SELECT COUNT(*) FROM english_writing_resource_tag x JOIN english_taxonomy_term t ON t.id=x.term_id WHERE x.resource_id=? AND t.dimension=? AND t.enabled=1",Integer.class,id,d);return c!=null&&c>0;}
    private void replaceTags(Long id,List<Long> ids){jdbc.update("DELETE FROM english_writing_resource_tag WHERE resource_id=?",id);for(Long term:new LinkedHashSet<>(ids==null?List.of():ids)){String d=jdbc.query("SELECT dimension FROM english_taxonomy_term WHERE id=? AND enabled=1",rs->rs.next()?rs.getString(1):null,term);if(d==null||!(d.equals("TOPIC")||d.equals("GENRE")||d.equals("FUNCTION")||d.equals("ABILITY")))invalid("Invalid writing tag");jdbc.update("INSERT INTO english_writing_resource_tag(resource_id,term_id) VALUES (?,?)",id,term);}}
    private Map<Long,List<WritingTagRef>> tags(List<Long> ids){if(ids.isEmpty())return Map.of();String in=String.join(",",ids.stream().map(String::valueOf).toList());Map<Long,List<WritingTagRef>> out=new LinkedHashMap<>();jdbc.query("SELECT x.resource_id,t.id,t.name,t.slug,t.dimension FROM english_writing_resource_tag x JOIN english_taxonomy_term t ON t.id=x.term_id WHERE x.resource_id IN ("+in+") ORDER BY t.dimension,t.sort_order,t.id",rs->{while(rs.next())out.computeIfAbsent(rs.getLong(1),k->new ArrayList<>()).add(new WritingTagRef(rs.getLong(2),rs.getString(3),rs.getString(4),rs.getString(5)));return null;});return out;}
    private WritingResourceView mapView(ResultSet rs,int n)throws SQLException{Long id=rs.getLong("id");return new WritingResourceView(id,rs.getString("resource_kind"),rs.getString("expression_level"),rs.getString("title"),rs.getString("slug"),rs.getString("summary"),rs.getString("body_markdown"),nullable(rs,"cover_media_id"),rs.getString("cover_url"),rs.getString("cefr_level"),nullableInt(rs,"word_min"),nullableInt(rs,"word_max"),rs.getInt("estimated_minutes"),rs.getString("template_schema_json"),rs.getString("publish_status"),rs.getInt("sort_order"),format(rs,"published_at"),format(rs,"updated_at"),tags(List.of(id)).getOrDefault(id,List.of()));}
    private WritingResourceSummaryView summary(ResultSet rs)throws SQLException{return new WritingResourceSummaryView(rs.getLong("id"),rs.getString("resource_kind"),rs.getString("expression_level"),rs.getString("title"),rs.getString("slug"),rs.getString("summary"),rs.getString("cover_url"),rs.getString("cefr_level"),rs.getInt("estimated_minutes"),rs.getString("publish_status"),rs.getInt("sort_order"),format(rs,"updated_at"),List.of());}
    private WritingResource require(Long id){WritingResource e=mapper.selectById(id);if(e==null)throw new ApiException(HttpStatus.NOT_FOUND,"ENGLISH_WRITING_RESOURCE_NOT_FOUND","Resource not found","The writing resource does not exist.");return e;}
    private boolean slugExists(String slug){return mapper.selectCount(new LambdaQueryWrapper<WritingResource>().eq(WritingResource::getSlug,slug))>0;}
    private void assertSlug(String slug,Long excluded){LambdaQueryWrapper<WritingResource>w=new LambdaQueryWrapper<WritingResource>().eq(WritingResource::getSlug,slug.trim());if(excluded!=null)w.ne(WritingResource::getId,excluded);if(mapper.selectCount(w)>0)throw conflict();}
    private int nextOrder(){Integer v=jdbc.queryForObject("SELECT COALESCE(MAX(sort_order),0) FROM english_writing_resource",Integer.class);return(v==null?0:v)+10;}private void cefr(String v){Integer n=jdbc.queryForObject("SELECT COUNT(*) FROM english_cefr_standard WHERE level=?",Integer.class,v);if(n==null||n==0)invalid("Invalid CEFR level");}private void cover(Long id){if(id==null)return;Integer n=jdbc.queryForObject("SELECT COUNT(*) FROM media_asset WHERE id=? AND asset_type='IMAGE'",Integer.class,id);if(n==null||n==0)invalid("Cover must be an image");}private ApiException conflict(){return new ApiException(HttpStatus.CONFLICT,"ENGLISH_CONTENT_SLUG_CONFLICT","Slug already in use","Choose another stable slug.");}private ApiException unavailable(){return new ApiException(HttpStatus.NOT_FOUND,"ENGLISH_CONTENT_NOT_PUBLISHED","Content not available","The requested writing resource is not published.");}private void invalid(String s){throw new ApiException(HttpStatus.UNPROCESSABLE_ENTITY,"ENGLISH_WRITING_INVALID", "Invalid writing data",s);}private String clean(String s){return s==null||s.isBlank()?null:s.trim();}private String format(ResultSet rs,String col)throws SQLException{var t=rs.getTimestamp(col);return t==null?null:timezone.atSite(t.toLocalDateTime()).format(ISO);}private Long nullable(ResultSet rs,String c)throws SQLException{long x=rs.getLong(c);return rs.wasNull()?null:x;}private Integer nullableInt(ResultSet rs,String c)throws SQLException{int x=rs.getInt(c);return rs.wasNull()?null:x;}
}
