package com.starrainnotes.english.writing.service;

import com.baomidou.mybatisplus.core.conditions.query.LambdaQueryWrapper;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.starrainnotes.common.error.ApiException;
import com.starrainnotes.common.slug.NumericSlugGenerator;
import com.starrainnotes.english.writing.dto.*;
import com.starrainnotes.english.writing.entity.WritingPrompt;
import com.starrainnotes.english.writing.mapper.WritingPromptMapper;
import com.starrainnotes.site.service.SiteSettingsTimezone;
import org.springframework.dao.DuplicateKeyException;
import org.springframework.http.HttpStatus;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import java.sql.ResultSet; import java.sql.SQLException; import java.time.format.DateTimeFormatter; import java.util.*;

@Service
public class WritingPromptService {
 private static final DateTimeFormatter ISO=DateTimeFormatter.ISO_OFFSET_DATE_TIME;
 private static final String BASE="SELECT p.*,m.public_url cover_url FROM english_writing_prompt p LEFT JOIN media_asset m ON m.id=p.cover_media_id";
 private final WritingPromptMapper mapper; private final JdbcTemplate jdbc; private final ObjectMapper json; private final SiteSettingsTimezone timezone;
 public WritingPromptService(WritingPromptMapper mapper,JdbcTemplate jdbc,ObjectMapper json,SiteSettingsTimezone timezone){this.mapper=mapper;this.jdbc=jdbc;this.json=json;this.timezone=timezone;}
 @Transactional public WritingPromptView create(WritingPromptRequest r){validate(r);String slug=NumericSlugGenerator.forCreate(r.slug(),this::slugExists);WritingPrompt p=new WritingPrompt();apply(p,r,slug);p.setPublishStatus("DRAFT");p.setSortOrder(r.sortOrder()==null?next():r.sortOrder());try{mapper.insert(p);}catch(DuplicateKeyException e){throw conflict();}tags(p.getId(),r.tagIds());return get(p.getId());}
 @Transactional public WritingPromptView update(Long id,WritingPromptRequest r){WritingPrompt p=require(id);validate(r);String slug=NumericSlugGenerator.forUpdate(r.slug(),p.getSlug());slug(slug,id);apply(p,r,slug);try{mapper.updateById(p);}catch(DuplicateKeyException e){throw conflict();}tags(id,r.tagIds());return get(id);}
 public WritingPromptView get(Long id){require(id);return jdbc.queryForObject(BASE+" WHERE p.id=?",this::view,id);}
 public WritingPromptView publicGet(String slug){try{return jdbc.queryForObject(BASE+" WHERE p.slug=? AND p.publish_status='PUBLISHED'",this::view,slug);}catch(Exception e){throw unavailable();}}
 public WritingPageView<WritingPromptSummaryView> list(int page,int pageSize,String q,String cefr,String status,Long topic,Long genre){List<Object> a=new ArrayList<>();return page(page,pageSize,where(q,cefr,status,topic,genre,a),a);}
 public WritingPageView<WritingPromptSummaryView> publicList(int page,int size,String q,String cefr,Long topic,Long genre){List<Object>a=new ArrayList<>();return page(page,size,where(q,cefr,"PUBLISHED",topic,genre,a),a);}
 @Transactional public WritingPromptView publish(Long id){WritingPrompt p=require(id);List<String> bad=problems(p);if(!bad.isEmpty())throw new ApiException(HttpStatus.UNPROCESSABLE_ENTITY,"ENGLISH_WRITING_PUBLISH_INVALID","Cannot publish",String.join("; ",bad));jdbc.update("UPDATE english_writing_prompt SET publish_status='PUBLISHED',published_at=COALESCE(published_at,UTC_TIMESTAMP(6)) WHERE id=?",id);return get(id);}
 @Transactional public WritingPromptView withdraw(Long id){WritingPrompt p=require(id);if("DRAFT".equals(p.getPublishStatus()))throw new ApiException(HttpStatus.UNPROCESSABLE_ENTITY,"ENGLISH_INVALID_PUBLISH_TRANSITION","Invalid publish transition","A draft task cannot be withdrawn.");jdbc.update("UPDATE english_writing_prompt SET publish_status='WITHDRAWN' WHERE id=?",id);return get(id);}
 @Transactional public void delete(Long id){WritingPrompt p=require(id);if("PUBLISHED".equals(p.getPublishStatus()))throw new ApiException(HttpStatus.CONFLICT,"ENGLISH_WRITING_PUBLISHED_DELETE_FORBIDDEN","Published task cannot be deleted","Withdraw it first.");mapper.deleteById(id);}
 @Transactional public void move(Long id,int target){require(id);List<Long>ids=jdbc.queryForList("SELECT id FROM english_writing_prompt ORDER BY sort_order,id",Long.class);ids.remove(id);ids.add(Math.min(Math.max(0,target),ids.size()),id);for(int i=0;i<ids.size();i++)jdbc.update("UPDATE english_writing_prompt SET sort_order=? WHERE id=?",(i+1)*10,ids.get(i));}
 private WritingPageView<WritingPromptSummaryView> page(int page,int size,String where,List<Object>a){int p=Math.max(1,page),s=Math.min(50,Math.max(1,size));Long total=jdbc.queryForObject("SELECT COUNT(*) FROM english_writing_prompt p "+where,Long.class,a.toArray());List<WritingPromptSummaryView>rows=jdbc.query(BASE+" "+where+" ORDER BY p.sort_order,p.id LIMIT "+s+" OFFSET "+((p-1)*s),a.toArray(),(rs,n)->summary(rs));Map<Long,List<WritingTagRef>>t=loadTags(rows.stream().map(WritingPromptSummaryView::id).toList());return new WritingPageView<>(rows.stream().map(x->x.withTags(t.getOrDefault(x.id(),List.of()))).toList(),p,s,total==null?0:total,total==null||total==0?0:(int)((total+s-1)/s));}
 private String where(String q,String cefr,String status,Long topic,Long genre,List<Object>a){StringBuilder w=new StringBuilder("WHERE 1=1");if(q!=null&&!q.isBlank()){w.append(" AND (p.title LIKE ? OR p.summary LIKE ?)");a.add("%"+q.trim()+"%");a.add("%"+q.trim()+"%");}if(cefr!=null&&!cefr.isBlank()){w.append(" AND p.cefr_level=?");a.add(cefr);}if(status!=null&&!status.isBlank()){w.append(" AND p.publish_status=?");a.add(status);}tag(w,a,topic,"TOPIC");tag(w,a,genre,"GENRE");return w.toString();}private void tag(StringBuilder w,List<Object>a,Long id,String d){if(id!=null){w.append(" AND EXISTS (SELECT 1 FROM english_writing_prompt_tag x JOIN english_taxonomy_term t ON t.id=x.term_id WHERE x.prompt_id=p.id AND x.term_id=? AND t.dimension=?)");a.add(id);a.add(d);}}
 private void validate(WritingPromptRequest r){if(r.wordMin()<0||r.wordMax()<r.wordMin()||r.estimatedMinutes()<0)bad("Invalid word range or estimated time");cefr(r.cefrLevel());cover(r.coverMediaId());reference(r.templateResourceId(),"TEMPLATE");reference(r.modelResourceId(),"MODEL_ESSAY");rubric(r.rubricJson());checklist(r.checklistJson());}
 private void rubric(String raw){if(raw==null||raw.isBlank())return;try{JsonNode n=json.readTree(raw);if(!n.isArray())bad("Rubric must be an array");Set<String> names=new HashSet<>();int sum=0;for(JsonNode x:n){String name=x.path("name").asText();int score=x.path("maxScore").asInt(0);if(name.isBlank()||!names.add(name)||score<=0)bad("Invalid rubric item");sum+=score;}if(sum>100)bad("Rubric total cannot exceed 100");}catch(ApiException x){throw x;}catch(Exception x){bad("Invalid rubric JSON");}}
 private void checklist(String raw){if(raw==null||raw.isBlank())return;try{JsonNode n=json.readTree(raw);if(!n.isArray())bad("Checklist must be an array");Set<String>s=new HashSet<>();for(JsonNode x:n){String v=x.asText().trim();if(v.isBlank()||!s.add(v))bad("Invalid checklist item");}}catch(ApiException x){throw x;}catch(Exception x){bad("Invalid checklist JSON");}}
 private void apply(WritingPrompt p,WritingPromptRequest r,String slug){p.setTitle(r.title().trim());p.setSlug(slug);p.setSummary(r.summary().trim());p.setBackgroundMarkdown(r.backgroundMarkdown());p.setRequirementsMarkdown(r.requirementsMarkdown());p.setCefrLevel(r.cefrLevel());p.setWordMin(r.wordMin());p.setWordMax(r.wordMax());p.setEstimatedMinutes(r.estimatedMinutes());p.setRubricJson(clean(r.rubricJson()));p.setChecklistJson(clean(r.checklistJson()));p.setTemplateResourceId(r.templateResourceId());p.setModelResourceId(r.modelResourceId());p.setCoverMediaId(r.coverMediaId());if(r.sortOrder()!=null)p.setSortOrder(r.sortOrder());}
 private List<String> problems(WritingPrompt p){List<String>b=new ArrayList<>();if(p.getBackgroundMarkdown()==null||p.getBackgroundMarkdown().isBlank())b.add("背景不能为空");if(p.getRequirementsMarkdown()==null||p.getRequirementsMarkdown().isBlank())b.add("要求不能为空");if(!hasTag(p.getId()))b.add("至少需要一个主题或文体标签");if(p.getTemplateResourceId()!=null&&!publishedResource(p.getTemplateResourceId(),"TEMPLATE"))b.add("模板必须已发布");if(p.getModelResourceId()!=null&&!publishedResource(p.getModelResourceId(),"MODEL_ESSAY"))b.add("范文必须已发布");return b;}
 private void tags(Long id,List<Long>ids){jdbc.update("DELETE FROM english_writing_prompt_tag WHERE prompt_id=?",id);for(Long term:new LinkedHashSet<>(ids==null?List.of():ids)){String d=jdbc.query("SELECT dimension FROM english_taxonomy_term WHERE id=? AND enabled=1",rs->rs.next()?rs.getString(1):null,term);if(d==null||!(d.equals("TOPIC")||d.equals("GENRE")||d.equals("FUNCTION")||d.equals("ABILITY")))bad("Invalid writing tag");jdbc.update("INSERT INTO english_writing_prompt_tag(prompt_id,term_id) VALUES (?,?)",id,term);}}
 private Map<Long,List<WritingTagRef>>loadTags(List<Long>ids){if(ids.isEmpty())return Map.of();String in=String.join(",",ids.stream().map(String::valueOf).toList());Map<Long,List<WritingTagRef>>o=new LinkedHashMap<>();jdbc.query("SELECT x.prompt_id,t.id,t.name,t.slug,t.dimension FROM english_writing_prompt_tag x JOIN english_taxonomy_term t ON t.id=x.term_id WHERE x.prompt_id IN ("+in+") ORDER BY t.dimension,t.sort_order,t.id",rs->{while(rs.next())o.computeIfAbsent(rs.getLong(1),k->new ArrayList<>()).add(new WritingTagRef(rs.getLong(2),rs.getString(3),rs.getString(4),rs.getString(5)));return null;});return o;}
 private WritingPromptView view(ResultSet r,int n)throws SQLException{Long id=r.getLong("id");return new WritingPromptView(id,r.getString("title"),r.getString("slug"),r.getString("summary"),r.getString("background_markdown"),r.getString("requirements_markdown"),r.getString("cefr_level"),r.getInt("word_min"),r.getInt("word_max"),r.getInt("estimated_minutes"),r.getString("rubric_json"),r.getString("checklist_json"),nullable(r,"template_resource_id"),nullable(r,"model_resource_id"),nullable(r,"cover_media_id"),r.getString("cover_url"),r.getString("publish_status"),r.getInt("sort_order"),date(r,"published_at"),date(r,"updated_at"),loadTags(List.of(id)).getOrDefault(id,List.of()));}
 private WritingPromptSummaryView summary(ResultSet r)throws SQLException{return new WritingPromptSummaryView(r.getLong("id"),r.getString("title"),r.getString("slug"),r.getString("summary"),r.getString("cefr_level"),r.getInt("word_min"),r.getInt("word_max"),r.getInt("estimated_minutes"),r.getString("cover_url"),r.getString("publish_status"),r.getInt("sort_order"),date(r,"updated_at"),List.of());}
 private boolean slugExists(String s){return mapper.selectCount(new LambdaQueryWrapper<WritingPrompt>().eq(WritingPrompt::getSlug,s))>0;}
 private WritingPrompt require(Long id){WritingPrompt p=mapper.selectById(id);if(p==null)throw new ApiException(HttpStatus.NOT_FOUND,"ENGLISH_WRITING_PROMPT_NOT_FOUND","Task not found","The writing task does not exist.");return p;}private void slug(String s,Long except){var w=new LambdaQueryWrapper<WritingPrompt>().eq(WritingPrompt::getSlug,s.trim());if(except!=null)w.ne(WritingPrompt::getId,except);if(mapper.selectCount(w)>0)throw conflict();}private int next(){Integer x=jdbc.queryForObject("SELECT COALESCE(MAX(sort_order),0) FROM english_writing_prompt",Integer.class);return(x==null?0:x)+10;}private boolean hasTag(Long id){Integer x=jdbc.queryForObject("SELECT COUNT(*) FROM english_writing_prompt_tag x JOIN english_taxonomy_term t ON t.id=x.term_id WHERE x.prompt_id=? AND t.enabled=1 AND t.dimension IN ('TOPIC','GENRE')",Integer.class,id);return x!=null&&x>0;}private boolean publishedResource(Long id,String kind){Integer x=jdbc.queryForObject("SELECT COUNT(*) FROM english_writing_resource WHERE id=? AND resource_kind=? AND publish_status='PUBLISHED'",Integer.class,id,kind);return x!=null&&x>0;}private void reference(Long id,String kind){if(id==null)return;Integer x=jdbc.queryForObject("SELECT COUNT(*) FROM english_writing_resource WHERE id=? AND resource_kind=?",Integer.class,id,kind);if(x==null||x==0)bad("Invalid "+kind+" resource");}private void cefr(String v){Integer x=jdbc.queryForObject("SELECT COUNT(*) FROM english_cefr_standard WHERE level=?",Integer.class,v);if(x==null||x==0)bad("Invalid CEFR level");}private void cover(Long id){if(id==null)return;Integer x=jdbc.queryForObject("SELECT COUNT(*) FROM media_asset WHERE id=? AND asset_type='IMAGE'",Integer.class,id);if(x==null||x==0)bad("Cover must be an image");}private ApiException conflict(){return new ApiException(HttpStatus.CONFLICT,"ENGLISH_CONTENT_SLUG_CONFLICT","Slug already in use","Choose another stable slug.");}private ApiException unavailable(){return new ApiException(HttpStatus.NOT_FOUND,"ENGLISH_CONTENT_NOT_PUBLISHED","Content not available","The requested writing task is not published.");}private void bad(String s){throw new ApiException(HttpStatus.UNPROCESSABLE_ENTITY,"ENGLISH_WRITING_INVALID","Invalid writing data",s);}private String clean(String s){return s==null||s.isBlank()?null:s.trim();}private Long nullable(ResultSet r,String c)throws SQLException{long x=r.getLong(c);return r.wasNull()?null:x;}private String date(ResultSet r,String c)throws SQLException{var t=r.getTimestamp(c);return t==null?null:timezone.atSite(t.toLocalDateTime()).format(ISO);}
}
