/**
 * Client-side derived article outline entry (TOC): headings H2-H4 with
 * stable ids generated by the MarkdownRenderer.
 */
export interface OutlineItem {
  level: number
  id: string
  text: string
}
