import { get, post, put, patch } from '../../../shared/http'
const id = encodeURIComponent
const base = '/account/learning'
export const getChapterProgress = (chapterId) => get(`${base}/progress/chapters/${id(chapterId)}`)
export const saveChapterProgress = (chapterId, payload) => put(`${base}/progress/chapters/${id(chapterId)}`, payload)
export const completeChapter = (chapterId) => post(`${base}/progress/chapters/${id(chapterId)}/complete`)
export const getTutorialProgress = (tutorialId) => get(`${base}/progress/tutorials/${id(tutorialId)}`)
export const getRecentLearning = () => get(`${base}/recent`)
export const getOwnAnswer = (questionId) => get(`${base}/questions/${id(questionId)}/answer`)
export const saveOwnAnswer = (questionId, answerText, answerPhase = 'BEFORE_REFERENCE') => post(`${base}/questions/${id(questionId)}/versions`, { answerText, answerPhase })
export const getAnswerVersions = (questionId) => get(`${base}/questions/${id(questionId)}/versions`)
export const getOwnReferenceAnswer = (questionId) => get(`${base}/questions/${id(questionId)}/reference-answer`)
export const listStudyPlans = () => get(`${base}/plans`, { currentOnly: true })
export const getStudyPlan = (planId) => get(`${base}/plans/${id(planId)}`)
export const previewStudyPlan = (payload, planId) => post(`${base}/plans/preview${planId ? `?excludePlanId=${id(planId)}` : ''}`, payload)
export const createStudyPlan = (payload) => post(`${base}/plans`, payload)
export const updateStudyPlan = (planId, payload) => patch(`${base}/plans/${id(planId)}`, payload)
export const transitionStudyPlan = (planId, action) => post(`${base}/plans/${id(planId)}/${action}`)
export const listPlanTasks = (planId) => get(`${base}/plans/${id(planId)}/tasks`)
export const getStudyTask = (taskId) => get(`${base}/tasks/${id(taskId)}`)
export const startStudyTask = (taskId) => post(`${base}/tasks/${id(taskId)}/start`)
export const getStudyState = (chapterId, planId) => get(`${base}/chapters/${id(chapterId)}/study-state`, planId ? { planId } : undefined)
export const startInitialSession = (chapterId, taskId) => post(`${base}/chapters/${id(chapterId)}/sessions${taskId ? `?taskId=${id(taskId)}` : ''}`)
export const getLearningSession = (sessionId) => get(`${base}/sessions/${id(sessionId)}`)
export const revealCard = (sessionId, cardId) => post(`${base}/sessions/${id(sessionId)}/cards/${id(cardId)}/reveal`)
export const rateCard = (sessionId, cardId, rating) => post(`${base}/sessions/${id(sessionId)}/cards/${id(cardId)}/rate`, { rating })
export const getReviewSummary = () => get(`${base}/reviews/summary`)
export const getCurrentReview = () => get(`${base}/reviews/sessions/current`)
export const createReviewSession = (count, mode = 'RECOMMENDED') => post(`${base}/reviews/sessions`, { count, mode })
export const getReviewSession = (sessionId) => get(`${base}/reviews/sessions/${id(sessionId)}`)
export const abandonReviewSession = (sessionId) => post(`${base}/reviews/sessions/${id(sessionId)}/abandon`)
export const listMastery = () => get(`${base}/mastery`)
export const getLearningHistory = (params) => get(`${base}/history`, params)
export const getLearningStatistics = () => get(`${base}/statistics`)

export const getMasteryPage = (params) => get(`${base}/mastery/page`, params)
export const getMasteryOptions = () => get(`${base}/mastery/options`)
export const getHistoryOptions = () => get(`${base}/history/options`)
export const getPlanHistory = (params) => get(`${base}/plans/history`, params)
