<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { RouterLink } from 'vue-router'
import { fetchVocabularyProgress, type VocabularyProgressSummary } from '@/api/vocabulary'
import { REVIEW_INTERVAL_SECONDS, vocabularyStudyStorage } from '@/lib/vocabulary-study-storage'

const progress = ref<VocabularyProgressSummary | null>(null); const loading = ref(true); const error = ref(''); const transferMessage = ref('')
const curvePoints = computed(() => {
  const max = Math.log10(REVIEW_INTERVAL_SECONDS.at(-1) ?? 1)
  return REVIEW_INTERVAL_SECONDS.map((seconds, index) => `${20 + index * 62},${180 - (Math.log10(seconds) / max) * 150}`).join(' ')
})
async function load() { loading.value = true; try { progress.value = await fetchVocabularyProgress(); error.value = '' } catch (cause) { error.value = cause instanceof Error ? cause.message : '进度读取失败。' } finally { loading.value = false } }
async function exportData() { try { const blob = new Blob([await vocabularyStudyStorage.exportJson()], { type: 'application/json' }); const url = URL.createObjectURL(blob); const link = document.createElement('a'); link.href = url; link.download = `star-rain-vocabulary-${new Date().toISOString().slice(0, 10)}.json`; link.click(); URL.revokeObjectURL(url); transferMessage.value = '本机学习数据已导出。' } catch (cause) { transferMessage.value = cause instanceof Error ? cause.message : '导出失败。' } }
async function importData(event: Event) { const file = (event.target as HTMLInputElement).files?.[0]; if (!file) return; try { await vocabularyStudyStorage.importJson(await file.text()); transferMessage.value = '导入完成。'; await load() } catch (cause) { transferMessage.value = cause instanceof Error ? cause.message : '导入失败。' } finally { (event.target as HTMLInputElement).value = '' } }
function intervalLabel(seconds: number) { if (seconds < 3600) return `${seconds / 60} 分`; if (seconds < 86400) return `${seconds / 3600} 小时`; return `${seconds / 86400} 天` }
onMounted(load)
</script>

<template><section class="progress"><header><div><p>VOCABULARY PROGRESS</p><h1>单词学习进度</h1><span>这里展示计划间隔与真实完成记录，不把它伪装成记忆保持率。</span></div><div><RouterLink to="/english/vocabulary/study">今日学习</RouterLink><RouterLink to="/english/vocabulary">词汇总览</RouterLink></div></header><div v-if="loading" class="progress__state">正在统计…</div><div v-else-if="error" class="progress__state">{{ error }} <button @click="load">重试</button></div><template v-else-if="progress"><div class="progress__stats"><article><strong>{{ progress.activeWords }}</strong><span>计划内单词</span></article><article><strong>{{ progress.dueWords }}</strong><span>当前到期</span></article><article><strong>{{ progress.completedToday }}</strong><span>今日完成</span></article><article><strong>{{ progress.totalReviews }}</strong><span>累计复习</span></article></div><section class="progress__curve"><div><h2>固定复习间隔曲线</h2><p>完成次数越多，下次复习间隔逐级延长。</p></div><svg viewBox="0 0 620 210" role="img" aria-label="十阶段计划复习间隔折线"><line x1="20" y1="180" x2="600" y2="180"/><polyline :points="curvePoints"/><circle v-for="(_, index) in REVIEW_INTERVAL_SECONDS" :key="index" :cx="20 + index * 62" :cy="Number(curvePoints.split(' ')[index].split(',')[1])" r="4"/><text v-for="(seconds, index) in REVIEW_INTERVAL_SECONDS" :key="`t-${index}`" :x="20 + index * 62" y="202">{{ index + 1 }}</text></svg><div class="progress__intervals"><span v-for="(seconds,index) in REVIEW_INTERVAL_SECONDS" :key="seconds">{{ index + 1 }} · {{ intervalLabel(seconds) }}</span></div></section><section class="progress__history"><h2>最近真实复习</h2><div v-if="!progress.recentReviews.length" class="progress__state">完成一次复习后，这里会出现真实时间点。</div><article v-for="item in progress.recentReviews" :key="item.id ?? item.reviewSessionId"><div><strong>{{ item.word ?? `单词 #${item.wordId}` }}</strong><span>第 {{ item.reviewNumber }} 次 · {{ item.direction === 'EN_TO_ZH' ? '英译中' : '中译英' }}</span></div><div><time>{{ new Date(item.reviewedAt).toLocaleString() }}</time><span :class="item.timingStatus.toLowerCase()">{{ { NEW:'首次', EARLY:'提前', ON_TIME:'准时', OVERDUE:'逾期' }[item.timingStatus] ?? item.timingStatus }}</span></div></article></section><section class="progress__data"><h2>本机数据</h2><p>游客数据保存在当前浏览器，可导出备份或导入恢复。登录账号的数据由服务器保存。</p><div><button @click="exportData">导出 JSON</button><label>导入 JSON<input type="file" accept="application/json" @change="importData"></label></div><span>{{ transferMessage }}</span></section></template></section></template>

<style scoped>
.progress{padding-bottom:60px}.progress>header{display:flex;justify-content:space-between;align-items:flex-end;gap:24px;margin-bottom:30px}.progress>header p{color:var(--accent);letter-spacing:.16em}.progress>header h1{font-size:40px;margin:6px 0}.progress>header span,.progress__curve p,.progress__data p{color:var(--text-secondary)}.progress>header>div:last-child{display:flex;gap:10px}.progress>header a,.progress__data button,.progress__data label{padding:9px 14px;border:1px solid var(--border);border-radius:9px;color:var(--text-secondary);cursor:pointer}.progress__stats{display:grid;grid-template-columns:repeat(4,1fr);gap:14px}.progress__stats article{display:grid;gap:5px;padding:20px;border:1px solid var(--border);border-radius:14px;background:var(--bg-surface)}.progress__stats strong{font-size:30px;color:var(--primary)}.progress__stats span{color:var(--text-muted)}.progress__curve,.progress__history,.progress__data{margin-top:24px;padding:24px;border:1px solid var(--border);border-radius:16px;background:var(--bg-surface)}.progress h2{font-size:22px;margin-bottom:6px}.progress__curve svg{width:100%;max-height:260px;margin-top:16px}.progress__curve line{stroke:var(--border)}.progress__curve polyline{fill:none;stroke:var(--primary);stroke-width:3}.progress__curve circle{fill:var(--accent)}.progress__curve text{fill:var(--text-muted);font-size:10px;text-anchor:middle}.progress__intervals{display:flex;flex-wrap:wrap;gap:8px}.progress__intervals span{padding:4px 8px;border:1px solid var(--border);border-radius:999px;font-size:12px;color:var(--text-muted)}.progress__history article{display:flex;justify-content:space-between;gap:18px;padding:14px 0;border-bottom:1px solid var(--border)}.progress__history article>div{display:flex;gap:10px}.progress__history span,.progress__history time{font-size:13px;color:var(--text-muted)}.progress__history .early{color:var(--accent)}.progress__history .on_time{color:var(--primary)}.progress__history .overdue{color:#d45858}.progress__data div{display:flex;gap:10px;margin-top:16px}.progress__data button,.progress__data label{background:transparent}.progress__data input{display:none}.progress__data>span,.progress__state{display:block;margin-top:12px;color:var(--text-muted)}
@media(max-width:700px){.progress>header{align-items:flex-start;flex-direction:column}.progress__stats{grid-template-columns:repeat(2,1fr)}.progress__history article,.progress__history article>div{flex-direction:column}.progress__curve,.progress__history,.progress__data{padding:18px}}
</style>
