<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { fetchPublicWritingPrompts, fetchPublicWritingResources, type WritingPromptSummary, type WritingResourceSummary } from '@/api/writing'
const resources=ref<WritingResourceSummary[]>([]),prompts=ref<WritingPromptSummary[]>([]),loading=ref(true)
onMounted(async()=>{try{[resources.value,prompts.value]=await Promise.all([fetchPublicWritingResources({page:1,pageSize:12}),fetchPublicWritingPrompts({page:1,pageSize:12})]).then(([r,p])=>[r.items,p.items])}finally{loading.value=false}})
const label=(x:string)=>({EXPRESSION_LESSON:'表达训练',GENRE_LESSON:'文体训练',MODEL_ESSAY:'范文库',TEMPLATE:'写作模板'}[x]||x)
</script>
<template><section class="writing"><header><p>ENGLISH WRITING · BUILD WITH CLARITY</p><h1>写作中心</h1><span>从句子、段落、衔接到风格；用课程、范文、模板和练习建立可复用的表达能力。</span></header><div v-loading="loading"><section><div class="head"><h2>写作路径</h2><span>四类资源，循序完成表达训练</span></div><div class="grid"><RouterLink v-for="x in resources" :key="x.id" :to="`/english/writing/resources/${x.slug}`" class="card"><div class="kind">{{label(x.resourceKind)}} · {{x.cefrLevel}}</div><h3>{{x.title}}</h3><p>{{x.summary}}</p><div><i v-for="t in x.tags" :key="t.id">{{t.name}}</i></div><b>开始学习 →</b></RouterLink><p v-if="!resources.length&&!loading" class="empty">资源正在建设中。</p></div></section><section><div class="head"><h2>开始练习</h2><span>在浏览器本地保存草稿，完成后按清单自评</span></div><div class="grid"><RouterLink v-for="x in prompts" :key="x.id" :to="`/english/writing/practice/${x.slug}`" class="card card--prompt"><div class="kind">WRITING PRACTICE · {{x.cefrLevel}}</div><h3>{{x.title}}</h3><p>{{x.summary}}</p><b>{{x.wordMin}}–{{x.wordMax}} 词 · {{x.estimatedMinutes}} 分钟 →</b></RouterLink><p v-if="!prompts.length&&!loading" class="empty">练习任务正在准备中。</p></div></section></div></section></template>
<style scoped>.writing{max-width:1280px;margin:auto}.writing>header{padding:30px 0 28px}.writing>header p,.kind{color:var(--accent);font-size:11px;letter-spacing:.14em;font-weight:800}.writing h1{font-size:42px;margin:8px 0}.writing>header span,.head span,.card p{color:var(--text-secondary)}section section{margin-top:35px}.head{display:flex;justify-content:space-between;align-items:baseline;margin-bottom:14px}.head h2{margin:0;font-size:21px}.head span{font-size:13px}.grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(255px,1fr));gap:14px}.card{min-height:210px;display:flex;flex-direction:column;padding:19px;border:1px solid var(--border);border-radius:18px;background:var(--bg-surface);color:inherit;transition:transform .16s ease,border-color .16s ease}.card:hover{transform:translateY(-3px);border-color:var(--primary)}.card h3{font-size:19px;margin:10px 0 7px}.card p{font-size:13px;line-height:1.6;margin:0}.card div:not(.kind){display:flex;gap:4px;flex-wrap:wrap;margin-top:12px}.card i{font-size:10px;font-style:normal;padding:2px 7px;border:1px solid var(--border);border-radius:999px}.card b{margin-top:auto;padding-top:14px;color:var(--primary);font-size:13px}.card--prompt{background:linear-gradient(135deg,color-mix(in srgb,var(--primary) 10%,var(--bg-surface)),var(--bg-surface))}.empty{color:var(--text-muted);grid-column:1/-1}@media(max-width:600px){.writing h1{font-size:32px}.head{display:block}.head span{display:block;margin-top:4px}.grid{grid-template-columns:1fr}}@media(prefers-reduced-motion:reduce){.card{transition:none}.card:hover{transform:none}}</style>
