<script setup lang="ts">
import { computed, onMounted, ref, watch } from 'vue'
import { useRoute } from 'vue-router'
import MarkdownRenderer from '@/components/MarkdownRenderer.vue'
import { fetchPublicWritingPrompt, fetchPublicWritingResource, type WritingPrompt, type WritingResource } from '@/api/writing'
const route=useRoute();const prompt=computed(()=>route.path.includes('/practice/'));const item=ref<WritingResource|WritingPrompt>();const draft=ref('');const key=computed(()=>`srn-english-writing-draft-v1:${route.params.slug}`)
async function load(){item.value=undefined;try{item.value=prompt.value?await fetchPublicWritingPrompt(String(route.params.slug)):await fetchPublicWritingResource(String(route.params.slug));if(prompt.value){try{draft.value=localStorage.getItem(key.value)||''}catch{}}}catch{}}
function saveDraft(){try{localStorage.setItem(key.value,draft.value)}catch{}}function clear(){if(confirm('清除本地草稿？')){draft.value='';try{localStorage.removeItem(key.value)}catch{}}}onMounted(()=>void load());watch(()=>route.params.slug,()=>void load())
</script>
<template><section v-if="item" class="writing-detail"><header><p>ENGLISH WRITING · {{prompt?'PRACTICE':'LEARNING'}}</p><h1>{{item.title}}</h1><span>{{item.summary}}</span><div class="meta">{{item.cefrLevel}} · {{item.estimatedMinutes}} 分钟</div></header><div v-if="!prompt" class="prose"><MarkdownRenderer :source="(item as WritingResource).bodyMarkdown"/></div><template v-else><div class="practice"><article><h2>任务背景</h2><MarkdownRenderer :source="(item as WritingPrompt).backgroundMarkdown"/><h2>写作要求</h2><MarkdownRenderer :source="(item as WritingPrompt).requirementsMarkdown"/></article><aside><b>词数目标</b><strong>{{(item as WritingPrompt).wordMin}}–{{(item as WritingPrompt).wordMax}} 词</strong><b>自检提示</b><span>草稿仅保存在当前浏览器；提交前检查结构、衔接和表达。</span></aside><section class="editor"><div><h2>开始写作</h2><span>{{draft.trim()?draft.trim().split(/\s+/).length:0}} 词</span></div><textarea v-model="draft" placeholder="在这里完成你的英文写作…" @input="saveDraft"/><el-button link type="danger" @click="clear">清除本地草稿</el-button></section></div></template></section><section v-else class="missing">内容不存在或尚未发布。</section></template>
<style scoped>.writing-detail{max-width:920px;margin:auto}.writing-detail header{padding:34px 0 28px;border-bottom:1px solid var(--border)}header p{font-size:11px;font-weight:800;letter-spacing:.14em;color:var(--accent);margin:0}header h1{font-size:38px;margin:8px 0}header span{color:var(--text-secondary);line-height:1.6}.meta{color:var(--primary);font-size:13px;margin-top:15px}.prose{max-width:760px;margin:28px auto}.practice{display:grid;grid-template-columns:minmax(0,1fr) 220px;gap:28px;margin-top:28px}.practice aside{height:max-content;padding:16px;border:1px solid var(--border);border-radius:14px;background:var(--bg-surface);display:flex;flex-direction:column;gap:7px;font-size:13px;color:var(--text-secondary)}.practice aside strong{font-size:23px;color:var(--primary)}.editor{grid-column:1/-1}.editor>div{display:flex;justify-content:space-between;align-items:baseline}.editor textarea{width:100%;box-sizing:border-box;min-height:360px;padding:16px;border:1px solid var(--border);border-radius:12px;background:var(--bg-surface);color:var(--text-primary);font:15px/1.7 ui-monospace,monospace;resize:vertical}.missing{padding:60px;text-align:center;color:var(--text-muted)}@media(max-width:720px){header h1{font-size:30px}.practice{grid-template-columns:1fr}.practice aside{order:-1}.editor textarea{min-height:280px}}</style>
